# YOUR NAME OR TITLE OF YOUR SITE
name: 

# YOUR BRAND/PERSONAL TAGLINE
tagline: Há mais de 13 anos realizando sonhos!
# YOUR/BRAND IMAGE URL
Image_URL: https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRjV_9ys7FtNW4j4ficLpZEoA7Hlc9hh8BQw7cCAFKX8w&s

# CHANGE THE BACKGROUND IMAGE OF THE WEBSITE BY JUST ADDING THE IMAGE URL
Cover_Image: https://picsum.photos/1080?nocache=

# SOCIAL MEDIA
links:

  # IF YOU DON'T WANT TO USE ANY OF THE FOLLOWING, JUST LEAVE THE URL BLANK
    
    # FACEBOOK
  - Name: Facebook
    URL: https://www.facebook.com
    Username: cfcavenidajd
    Color: '#3b5998'
    Icon-Class: fab fa-facebook

     # TWITTER
  - Name: João Durval
    URL: https://wa.me/557536167104?text=Ol%C3%A1%2C+Vim+atrav%C3%A9s+do+site.+Poderia+me+ajudar%3F
    Username: 
    Color: '#00FF00'
    Icon-Class: fa fa-whatsapp

    # INSTAGRAM
  - Name: Instagram
    URL: https://www.instagram.com
    Username: autoescolaavenida.fsa
    Color: '#DD2A7B'
    Icon-Class: fab fa-instagram

    # TWITTER
  - Name: SIM 
    URL: https://wa.me/message/IME2SXQQTUKHM1
    Username: 
    Color: '#00FF00'
    Icon-Class: fa fa-whatsapp
  
    # YOUTUBE
 # - Name: YouTube
   # URL: https://www.youtube.com/channel
  #  Username: UCS3zvA_2r1iGT7MB3NVCGAw
   # Color: '#ff0000'
   # Icon-Class: fab fa-youtube

  
# YOU CAN REMOVE FOOTER COMPLETELY BY SIMPLY REMOVING EITHER THE YES OR REMOVING THE FOOTER STATEMENT BELOW COMPLETELY
footer: 'Yes'

# STOP EDITING HERE ---------- YOU'VE REACHED THE END OF THE CONFIGURATION

# Compress
compress_html:
  clippings: all

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Icon

# Base URL
# baseurl: /links

# Default Markdown Engine
markdown: kramdown
